dumpfile        800K_2E5frames_10fs.dump
Natom           2048
Nstep           200000
type            0
timestep        0.01
Nfreq           1000
Nevery          10
Nrepeat         10000
Rcut1           0
Rcut2           6
qmax            2.5